# Dependencies
markdown:         kramdown
highlighter:      rouge

# Languages
languages: ["en", "fr"]
defaultLang: en
languageNames:
  en: English
  fr: Français

# Setup
# title:            Michael Dow
# tagline:          Linguist
# description:      Professional page & blog
url:              https://mcdowlinguist.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Michael Dow'
  url:            https://twitter.com/mcdowlinguist
disqus:
  shortname:      mcdowlinguist
paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-multiple-languages-plugin

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

exclude: [vendor]